language: java
script: ./build-snake

notifications:
  email:
    recipients:
      - kjdevocht@gmail.com
      - daniel.l.carrier@gmail.com
      - dbstandiford@gmail.com
      - djhaskin987@gmail.com
    on_success: change
    on_failure: change

after_success:
    - "scp -r coverage-reports dhaskin@schizo.cs.byu.edu:public_html/"
    - "scp -r doc dhaskin@schizo.cs.byu.edu:public_html/"
jdk:
    - oraclejdk7
    - oraclejdk6
    - openjdk7
    - openjdk6
