language: java
script: ./build-snake

notifications:
  email:
    recipients:
      - kidevocht@gmail.com
      - daniel.l.carrier@gmail.com
      - dbstandifor@gmail.com
      - djhaskin987@gmail.com
    on_success: change
    on_failure: change

jdk:
    - oraclejdk7
    - oraclejdk6
    - openjdk7
    - openjdk6
