package model;

public enum ModelActions {
	INSERT_STORAGE_UNIT,
	EDIT_STORAGE_UNIT,
	REMOVE_STORAGE_UNIT,
	INSERT_PRODUCT_GROUP,
	EDIT_PRODUCT_GROUP,
	INSERT_ITEMS,
	UNDO_INSERT_ITEMS,
	UNDO_INSERT_PRODUCT_AND_ITEMS,
	UNDO_INSERT_NEW_PRODUCT_AND_ITEMS,
	REMOVE_ITEMS,
	TRANSFER_ITEMS,
	EDIT_ITEM,
	MOVE_ITEM,
	INSERT_PRODUCT,
	EDIT_PRODUCT,
	TRANSFER_PRODUCT,
}
