package model;

public enum ModelActions {
	INSERT_STORAGE_UNIT,
	EDIT_STORAGE_UNIT,
	INSERT_PRODUCT_GROUP,
	EDIT_PRODUCT_GROUP,
	INSERT_ITEMS,
	REMOVE_ITEMS,
	TRANSFER_ITEMS,
	EDIT_ITEM,
	INSERT_PRODUCT,
	EDIT_PRODUCT
}
